### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Misat11** [ScreamingSandals/SimpleInventories-IDE#1]
- [ ] Make auto complete of groovy methods
- [ ] Make auto complete of Material names
- [ ] Run auto preview
- [ ] Make categories usable
- [ ] Add items picker that will automatically generate code to the groovy

**Comment by linusstretchtips** [comment]
:pagChomp: :pagChomp: :pagChomp: :pagChomp: :pagChomp:

**Comment by Misat11** [comment]
Are you okay?

**Comment by linusstretchtips** [comment]
yea xdd
